name: winkl_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_storage: ^2.0.3
  dio: ^4.0.4
  cached_network_image: ^3.1.0+1
  inview_notifier_list: ^2.0.0
  video_player: ^2.2.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_semi_bold_italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_bold_italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_bold_italic.ttf
          weight: 800
          style: italic

    - family: ci
      fonts:
        - asset: assets/fonts/custom_icons.ttf
          weight: 600

    - family: lob
      fonts:
        - asset: assets/fonts/lobster.ttf
    - family: pac
      fonts:
        - asset: assets/fonts/pacifico.ttf